### ISSUE TITLE
Cannot compile click linux module

### ISSUE THREAD

**Issue by nikhildps** [kohler/click#200]
I am trying to compile the click linux module on ubuntu set up on virtual box 

but i am getting the error:

Your Linux kernel header files cause errors when included by a C++ program.

Click modifies the Linux kernel's header files to make them work with
C++, using the program 'linuxmodule/fixincludes.pl'. It looks like
your kernel header files have features that 'linuxmodule/fixincludes.pl'
doesn't know how to fix. You can report this error to us on the Click
mailing list, or, even better, try to fix the error. See the config.log
file for more information on the error.

I tried to run the following command
sudo ./configure --with-linux=/usr/src/linux-headers-3.16.0-30-generic --with-linux-map=/boot/System.map-3.16.0-30-generic --enable-linuxmodule

and based on devious posts I also do ln -s ../generated/autoconf.h inside /usr/src/linux-headers-3.16.0-30-generic/include/linux. 

Please help me

**Comment by MappaM** [comment]
Did you also merged the headers-common with headers-amd64 (or other arch-specific folder) before the ln -s autoconf.h ?

mkdir /usr/src/linux-headers-merged/
cp -r /usr/src/linux-headers-*-common/* /usr/src/linux-headers-merged/
cp -r /usr/src/linux-headers-*-amd64/* /usr/src/linux-headers-merged/
then the ln -s.
And use the linux-headers-merged as the --with-linux path

I also have a problem which appeared recently with proclikefs during make, solved by doing : 
sed -i 's/d_u.d_child/d_child/' linuxmodule/proclikefs.c
And have another make error corrected by adding this line in include/click-linuxmodule/include0/asm/barrier.h : 
#define alternative(oldinstr, newinstr, feature)                        \
        asm volatile (ALTERNATIVE(oldinstr, newinstr, feature) : : : "memory");

**Comment by yahyaezzeldin** [comment]
I have the same problem, but even doing this linking, it isn't fixed.
It still says the same 

=========================================

Your Linux kernel header files cause errors when included by a C++ program.

Click modifies the Linux kernel's header files to make them work with
C++, using the program 'linuxmodule/fixincludes.pl'. It looks like
your kernel header files have features that 'linuxmodule/fixincludes.pl'
doesn't know how to fix. You can report this error to us on the Click
mailing list, or, even better, try to fix the error. See the config.log
file for more information on the error.

=========================================


Ubuntu has only linux-headers-3.16.0-30-generic folder with no arch-specific folder.

**Comment by wtao0221** [comment]
@yahyaezzeldin I come into the same problem, do you fix it now?
